### ISSUE TITLE
 error: couldn't connect to server: EOF reached (code 1) (make sure server is running and you are connecting to the correct RPC port)

### ISSUE THREAD

**Issue by ceyhunyor** [marmarachain/marmara-connector#17]
error: couldn't connect to server: EOF reached (code 1) (make sure server is running and you are connecting to the correct RPC port)
![Ekran görüntüsü 2021-10-12 210255](https://user-images.githubusercontent.com/7870844/137006792-4523cd7c-e578-4890-b1ce-5cf28c916c93.png)

**Comment by rumeysayilmaz** [comment]
Error handling has been added to Marmara Connector 0.3.0-alpha release in case where Marmara chain doesn't start. The error you have reported is related to Marmarachain. To resolve this, for Windows please locate to the directory where Marmara is installed (C:\Users\{your_computer_username}\marmara) and right click and run the MCL_start.bat with admin rights. You should be able to start the chain in this way.

You can check if the chain is running by issuing the following command in command terminal. This command is used to check the pid of komodod.

`tasklist | findstr komodod`

If there is no return, it means that the marmara deamon has not started.
